language core;

extend with #exceptions, #exception-type-declaration;

exception type = Nat

fn main(n : Nat) -> Nat {
  return try { throw(succ(0)) } with { throw(0) }
}
